# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c9c8f24d7361b9c38cf234b838278e0b68d266ca2c3c03047c678b383291f2b3fff70b076043203f4b24384aaf5b4bbd5e10ba6260704c16b92eac9b502a59f

test:
  secret_key_base: 6526c9ba76c644c977d99b2abcf0e0e47320c723c1b460eee80c9754278850a0aa2352329dfbfcb27deee3b23f15d65a8a1723a2137821fc58830e2c67c15bd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
